# Generated by Django 3.1.6 on 2021-02-13 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210211_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_level',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent', to='posts.comment'),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reply', to='posts.comment'),
        ),
    ]
