# Generated by Django 3.1.6 on 2021-02-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210213_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_level',
            field=models.IntegerField(default=0),
        ),
    ]
