# Generated by Django 3.1.6 on 2021-02-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='headline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
