# Generated by Django 3.1.6 on 2021-02-17 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_auto_20210215_1251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
