# Generated by Django 3.1.6 on 2021-02-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.SlugField(error_messages={'unique': 'A user with that username already exists.'}, max_length=40, unique=True, verbose_name='username'),
        ),
    ]
